# pd.DataFrame()

A function from the Pandas library that creates a DataFrame, which is a 2-dimensional labeled data structure 
similar to a table in a spreadsheet or a SQL database.


# What is a DataFrame?

- A **DataFrame** is one of the core data structures in Pandas.
- It organizes data in rows and columns, making it easier to manipulate, analyze, and visualize data.
- You can think of a DataFrame as a table where:
    - **Rows** represent individual observations or records.
    - **Columns** represent variables or features.


# Purpose of pd.DataFrame()
- The pd.DataFrame() function is used to create a DataFrame from various types of data sources, such as:
    - Lists
    - Dictionaries
    - NumPy arrays
    - Existing DataFrames or Series
    - External files (e.g., CSV, Excel)

In [3]:
import pandas as pd
import numpy as np

# Example DataFrame
images = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(images) 
print()
print(images.values)


   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

[[1 2 3]
 [4 5 6]
 [7 8 9]]


![images.values](img/values.png)

# images.values[9,:]

![images.values_function](img/values_fn.png)

In [1]:
import pandas as pd

# Create a DataFrame
data = pd.DataFrame({'A': range(10), 'B': range(10, 20), 'C': range(20, 30)})

print("DataFrame:\n", data)
print("\nRow 9, all columns:\n", data.values[9, :])



DataFrame:
    A   B   C
0  0  10  20
1  1  11  21
2  2  12  22
3  3  13  23
4  4  14  24
5  5  15  25
6  6  16  26
7  7  17  27
8  8  18  28
9  9  19  29

Row 9, all columns:
 [ 9 19 29]


# Example 2: Access a Single Element
If you use only`[row, col]` indexing instead of `[:]`:

In [3]:
print("Value in row 9, column 1 (column 'B'):", data.values[9, 1])

Value in row 9, column 1 (column 'B'): 19


# Example 3: Extract All Rows for a Column

In [4]:
print("All rows, column 2 (column 'C'):\n", data.values[:, 2])

All rows, column 2 (column 'C'):
 [20 21 22 23 24 25 26 27 28 29]


# Example 4: Subset of Rows and Columns

In [5]:
print("Rows 5 to 9, columns 1 to 2:\n", data.values[5:10, 1:3])

Rows 5 to 9, columns 1 to 2:
 [[15 25]
 [16 26]
 [17 27]
 [18 28]
 [19 29]]
