## Yuxiao Zheng | Homework 2


#### import these lirbaries to call some methods help calculate A = LU

In [94]:
import math
import numpy as np

# Routine to compute matrix inverses
import numpy.linalg as la  # for la.inv

# LU decompostion algs are found in the scipy library, not in n
import scipy.linalg as sa  # for sa.lu


### Calculate A = LU

1. init a original Matrix
2. To find A = LU
3. call lu() method, take this current matrix as parameter
4. return L and U
5. Note: Since there a zero appears on the diagnoal, I need to swap the Row 1 and Row 2 in my written solution. For SciPy's LU Decomposition, it is with Permutation so the solutions are same.
6. check my ansower in Homework_2 Linear Algebra Part A: (the Python lirbary's solution is same with my hand written solution)

In [95]:
# a zero appears on the diagnoal
A = np.array([[0, 1, 2], [2, 4, 4], [1, 1, 1]]) 
P, L, U = sa.lu(A)

## print current matrix L
print(L)

## print current matrix U
print(U)

## print original matrix
ans = L @ U
print(ans)

[[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.5 -1.   1. ]]
[[2. 4. 4.]
 [0. 1. 2.]
 [0. 0. 1.]]
[[2. 4. 4.]
 [0. 1. 2.]
 [1. 1. 1.]]


### Compute the inverse of the matrix

1. init a original Matrix
2. call .inv() method to take a Matrix as the parameter
3. return an inverse of the original Matrix
4. check my ansower in Homework_2 Linear Algebra Part B: (the Python lirbary's solution is same with my hand written solution)

In [96]:
A = np.array([[0, 1, 2], [2, 4, 4], [1, 1, 1]])
A_inverse = la.inv(A)

print(A_inverse)

[[ 0.  -0.5  2. ]
 [-1.   1.  -2. ]
 [ 1.  -0.5  1. ]]


### Compute the LU decomposition of this tri-diagonal matrix with Permutation (Pivoting), to avoid a zero appear on the diagonal
1. init an original Matrix
2. To find A = LU
3. call .lu() method, take this current matrix as parameter 
4. return L and U
5. Note: the solution is that it will swap the rows and I am performing LU decomposition with permutation
6. check my ansower in Homework_2 Linear Algebra Part C: (the Python lirbary's solution is different with my hand written solution)


In [97]:
A = np.array([[1, 2, 0], [2, 5, 5], [0, 5, 26]])

### L, U that I got, are the A = LU with permutation and swap rows
P, L, U = sa.lu(A)

# Display the results
print("Lower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)

Lower Triangular Matrix L:
[[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.5 -0.1  1. ]]

Upper Triangular Matrix U:
[[ 2.   5.   5. ]
 [ 0.   5.  26. ]
 [ 0.   0.   0.1]]


###  Compute the LU decomposition of this tri-diagonal matrix without Permutation (No Pivoting)

1. init an original Matrix
2. To find A = LU
3. call LUdecomp_no_pivot() method, take this current matrix as parameter 
4. return L and U without swap rows (No Pivoting)
5. Note: the solution is that I am performing LU decomposition without permutation
6. check my ansower in Homework_2 Linear Algebra Part C: (the Python lirbary's solution is same with my hand written solution)

In [98]:
# For this function, I get the L and U without swap Rows to get the solution what I expected.
# Function to perform LU decomposition without pivoting, I don't swap rows
def LUdecomp_no_pivot(a):
    n = len(a)
    L = np.eye(n)  # Initialize L as the identity matrix
    U = a.copy()  # Initialize U as a copy of the original matrix

    for i in range(n):
        for j in range(i + 1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered, this method cannot handle it without row swaps.")
            # Calculate the multiplier for the current row
            L[j, i] = U[j, i] / U[i, i]
            # Update the row of U
            U[j, i:n] = U[j, i:n] - L[j, i] * U[i, i:n]

    return L, U


A = np.array([[1, 2, 0], [2, 5, 5], [0, 5, 26]])

# Perform LU decomposition without pivoting
L, U = LUdecomp_no_pivot(A)

# Display the results
print("Lower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)



Lower Triangular Matrix L:
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 5. 1.]]

Upper Triangular Matrix U:
[[1 2 0]
 [0 1 5]
 [0 0 1]]
