In [1]:
import math
import numpy as np

# Routine to compute matrix inverses
import numpy.linalg as la  # for la.inv

# LU decompostion algs are found in the scipy library, not in n
import scipy.linalg as sa  # for sa.lu

In [2]:
A = np.array([[1, 2, 0, 1], [0, 1, 1, 0], [1, 2, 0, 1]])
P, L, U = sa.lu(A)

print(L)
print(U)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]
[[1. 2. 0. 1.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [19]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[1, 2, 0, 1],
                [0, 1, 1, 0],
                [1, 2, 0, 1]])

# Compute the column space
column_space = A.columnspace()

# Print the basis for the column space
print("Basis for the column space:")
print(column_space)





# for vec in column_space:
#     print(vec)

Basis for the column space:
[Matrix([
[1],
[0],
[1]]), Matrix([
[2],
[1],
[2]])]
